### ISSUE TITLE
Routes for Allowed IPs not set correctly

### ISSUE THREAD

**Issue by lxp** [Lochnair/vyatta-wireguard#53] opened 2018-05-04 17:27 UTC
This commit causes the allowed ips not to be set up during initial boot.
The routes are just missing.

https://github.com/Lochnair/vyatta-wireguard/commit/f7e009e2c15278e54753416a79dad3e83803ab52#diff-08f5a043988b5281617f6fb550a1aceb

**Comment by tssva** [comment] 2018-05-04 18:04
The issue was caused by commit 3d985167ef38c4df94b6da82f34d6d1939015f8b and should be fixed with PR #52

**Comment by Lochnair** [comment] 2018-05-04 18:09
I've uploaded new packages with the fixes from #52 included.

**Closed by Lochnair** 2018-05-04 18:09 UTC

**Comment by lxp** [comment] 2018-05-04 18:51
I think this is a separate issue, as I already had the fixes from PR #52 manually applied.
Without those fixes the wireguard interface wasn't even created.

**Comment by tssva** [comment] 2018-05-04 18:58
It is working here. Have you confirmed that route-allowed-ips is set to true?

**Comment by lxp** [comment] 2018-05-04 19:09
route-allowed-ips was set to true.
After booting, I only got a mysterious 0.0.0.0/32 route, but no route for the IP range set via allowed-ips.
I confirmed that allowed-ips was set correctly on the wireguard interface.
I can't check it again right now, I will have access to the EdgeRouter again on Monday.

**Comment by tssva** [comment] 2018-05-04 19:18
I'll take a look. Let me uninstall the latest version and start from scratch. I might have some remnant from development that is causing it to work here.

**Comment by tssva** [comment] 2018-05-04 20:36
I removed and reinstalled the wireguard package and experienced the issue. I have submitted a PR which should resolve it. 

I'm reopening this until someone besides myself can also confirm it is resolved.
